name: roulette
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flutter_scene: ^0.23.0
  flutter_scene_soloud: ^0.1.2
  vector_math: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^11.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/nicknames.txt
